# Lychee configuration for Zuplo docs

# Cache settings
cache = true
max_cache_age = "1d"

# Network settings
max_concurrency = 10
timeout = 20
max_retries = 2
retry_wait_time = 2


# Exclude private IPs
exclude_all_private = true

# Accept these status codes as valid
accept = [200, 201, 202, 203, 204, 301, 302, 303, 307, 308, 429]

# Exclude patterns
exclude = [    
  "github.com/zuplo/zudoku/edit/(.*)",
  "github.com/zuplo/zudoku/issues",
  "github.com/zuplo/zudoku",
  "https://zudoku.dev/docs/400",
  "https://zudoku.dev/docs/404",
  "https://zudoku.dev/docs/500",
  "https://zudoku.dev/400",
  "https://zudoku.dev/404",
  "https://zudoku.dev/500",
  "stackoverflow.com",
  "dashboard.clerk.com",
  "openid.net",
  "manage.auth0.com",

  "https://portal.azure.com/",

  # For some reason we see these false negatives:
  # > Network error: error sending request for url (https://shiki.style/themes) Maybe a certificate error?
  "https://shiki.style/",
]

# Headers to send with requests
[headers]
user_agent = "Mozilla/5.0 (compatible; lychee/0.19.1)"
accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"